version: '3.8'
services:
  server:
    image: philipdevdocker/server:v1.0.3
    restart: always
    ports:
        - '443:443'
        - '80:80'
    depends_on:
      - frontend
    volumes:
      - /home/philipdev/ssl:/etc/ssl/private
    environment:
      - SSL_CERT_FILE=/etc/ssl/private/fullchain.pem
      - SSL_KEY_FILE=/etc/ssl/private/privkey.pem

  frontend:
    image: philipdevdocker/frontend:v1.0.2
    restart: always
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
